<?php

// autoload-classmap.php @generated by Mozart

$srcstrauss = dirname(__FILE__);

return array(
   'BrianHenryIE\WC_Duplicate_Gateway\Pablo_Pacheco\WP_Namespace_Autoloader\WP_Namespace_Autoloader' => $srcstrauss . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Katzgrau\KLogger\Logger' => $srcstrauss . '/katzgrau/klogger/src/Logger.php',
   'BrianHenryIE\WC_Duplicate_Gateway\WPTRT\AdminNotices\Notices' => $srcstrauss . '/wptrt/admin-notices/src/Notices.php',
   'BrianHenryIE\WC_Duplicate_Gateway\WPTRT\AdminNotices\Dismiss' => $srcstrauss . '/wptrt/admin-notices/src/Dismiss.php',
   'BrianHenryIE\WC_Duplicate_Gateway\WPTRT\AdminNotices\Notice' => $srcstrauss . '/wptrt/admin-notices/src/Notice.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\woocommerce\Log_Handler' => $srcstrauss . '/brianhenryie/wp-logger/src/woocommerce/class-log-handler.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\includes\Functions' => $srcstrauss . '/brianhenryie/wp-logger/src/includes/class-functions.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\includes\Cron' => $srcstrauss . '/brianhenryie/wp-logger/src/includes/class-cron.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\includes\BH_WP_Logger' => $srcstrauss . '/brianhenryie/wp-logger/src/includes/class-bh-wp-logger.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\admin\Logs_Table' => $srcstrauss . '/brianhenryie/wp-logger/src/admin/class-logs-table.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\admin\Admin' => $srcstrauss . '/brianhenryie/wp-logger/src/admin/class-admin.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\admin\Plugins_Page' => $srcstrauss . '/brianhenryie/wp-logger/src/admin/class-plugins-page.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\admin\Logs_Page' => $srcstrauss . '/brianhenryie/wp-logger/src/admin/class-logs-page.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\API\Logger_Settings' => $srcstrauss . '/brianhenryie/wp-logger/src/API/class-logger-settings.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\API\Logger_Settings_Trait' => $srcstrauss . '/brianhenryie/wp-logger/src/API/trait-logger-settings.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\API\API_Interface' => $srcstrauss . '/brianhenryie/wp-logger/src/API/interface-api.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\API\Plugin_Helper' => $srcstrauss . '/brianhenryie/wp-logger/src/API/class-plugin-helper.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\API\Logger_Settings_Interface' => $srcstrauss . '/brianhenryie/wp-logger/src/API/interface-logger-settings.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\API\API' => $srcstrauss . '/brianhenryie/wp-logger/src/API/class-api.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\API\PHP_Error_Handler' => $srcstrauss . '/brianhenryie/wp-logger/src/API/class-php-error-handler.php',
   'BrianHenryIE\WC_Duplicate_Gateway\BrianHenryIE\WP_Logger\Logger' => $srcstrauss . '/brianhenryie/wp-logger/src/class-logger.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Spatie\Backtrace\Backtrace' => $srcstrauss . '/spatie/backtrace/src/Backtrace.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Spatie\Backtrace\File' => $srcstrauss . '/spatie/backtrace/src/File.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Spatie\Backtrace\CodeSnippet' => $srcstrauss . '/spatie/backtrace/src/CodeSnippet.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Spatie\Backtrace\Frame' => $srcstrauss . '/spatie/backtrace/src/Frame.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\LoggerAwareInterface' => $srcstrauss . '/psr/log/Psr/Log/LoggerAwareInterface.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\LogLevel' => $srcstrauss . '/psr/log/Psr/Log/LogLevel.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\Test\LoggerInterfaceTest' => $srcstrauss . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\Test\TestLogger' => $srcstrauss . '/psr/log/Psr/Log/Test/TestLogger.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\Test\DummyTest' => $srcstrauss . '/psr/log/Psr/Log/Test/DummyTest.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\LoggerAwareTrait' => $srcstrauss . '/psr/log/Psr/Log/LoggerAwareTrait.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\InvalidArgumentException' => $srcstrauss . '/psr/log/Psr/Log/InvalidArgumentException.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\NullLogger' => $srcstrauss . '/psr/log/Psr/Log/NullLogger.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\LoggerInterface' => $srcstrauss . '/psr/log/Psr/Log/LoggerInterface.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\LoggerTrait' => $srcstrauss . '/psr/log/Psr/Log/LoggerTrait.php',
   'BrianHenryIE\WC_Duplicate_Gateway\Psr\Log\AbstractLogger' => $srcstrauss . '/psr/log/Psr/Log/AbstractLogger.php',
);