<?php

// autoload-classmap.php @generated by Strauss

$srcstrauss = dirname(__FILE__);

return array(
   'BrianHenryIE\WC_Duplicate_Payment_Gateways\Pablo_Pacheco\WP_Namespace_Autoloader\WP_Namespace_Autoloader' => $srcstrauss . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
);